package httpx

const (
	ContentTypeAll                        = "*/*"
	ContentTypeApplicationAtomXml         = "application/atom+xml"
	ContentTypeApplicationCbor            = "application/cbor"
	ContentTypeApplicationFormUrlencoded  = "application/x-www-form-urlencoded"
	ContentTypeApplicationJson            = "application/json"
	ContentTypeApplicationJsonUtf8        = "application/json;charset=UTF-8"
	ContentTypeApplicationOctetStream     = "application/octet-stream"
	ContentTypeApplicationPdf             = "application/pdf"
	ContentTypeApplicationProblemJson     = "application/problem+json"
	ContentTypeApplicationProblemJsonUtf8 = "application/problem+json;charset=UTF-8"
	ContentTypeApplicationProblemXml      = "application/problem+xml"
	ContentTypeApplicationRssXml          = "application/rss+xml"
	ContentTypeApplicationStreamJson      = "application/stream+json"
	ContentTypeApplicationXhtmlXml        = "application/xhtml+xml"
	ContentTypeApplicationXml             = "application/xml"
	ContentTypeImageGif                   = "image/gif"
	ContentTypeImageJpeg                  = "image/jpeg"
	ContentTypeImagePng                   = "image/png"
	ContentTypeMultipartFormData          = "multipart/form-data"
	ContentTypeMultipartMixed             = "multipart/mixed"
	ContentTypeMultipartRelated           = "multipart/related"
	ContentTypeTextEventStream            = "text/event-stream"
	ContentTypeTextHtml                   = "text/html"
	ContentTypeTextMarkdown               = "text/markdown"
	ContentTypeTextPlain                  = "text/plain"
	ContentTypeTextXml                    = "text/xml"
)
